# Set new prefix
set-option -g prefix `
bind-key ` send-prefix

# Optionally unbind old prefix
#unbind C-b
#bind-key C-b send-prefix

# 0 too far from 1
set -g base-index 1

# Rebind split keys
bind | split-window -h
bind - split-window -v

# Tell tmux not to wait after the escape key is pressed
# Needed for kakoune and possibly other modal text editors
set -sg escape-time 0

# Rename window automatically
set -g automatic-rename on
set -g set-titles on

# Set tmux color settings
# Note: '*' is a regular expression that matches your external terminal's $TERM value, modify it if your terminal supports 24-bit true color
set -g default-terminal 'tmux-256color'
set-option -ga terminal-overrides ",*:RGB"

set -g history-limit 50000

bind-key g command-prompt -p "Move pane below" "move-pane -v -t %%"
bind-key G command-prompt -p "Move pane right" "move-pane -h -t %%"

# Vimify

setw -g mode-keys vi
set -g status-keys vi

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r M-h resize-pane -L 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-l resize-pane -R 5

# Reload tmux conf
bind r source-file ~/.tmux.conf

# Set status color
set -g status-style 'fg=default, bg=default'
