## BUILTIN CONFIGURATION

addhl -override global/ number-lines -relative
addhl -override global/ regex '\h+$' 0:Error

set global tabstop 4
set global indentwidth 4

#colorscheme gruvbox

# Select whole line, not including newline
map global normal "X" "xH"

# Make ctags easier
map global normal <c-]> <a-i>w:ctags-search<ret>

# Making commenting easier
map global normal "#" ": comment-line<ret>" -docstring "comment line"
map global normal "<a-#>" ": comment-block<ret>" -docstring "comment block"

# Copy/paste to/from clipboard
map global user "c" "<a-|> xclip -selection clipboard -in<ret>" -docstring "copy to clipboard"
map global user "p" "<!> xclip -selection clipboard -out<ret>" -docstring "paste from clipboard"

# Use ripgrep for searching files
set-option current grepcmd "rg --line-number --no-heading"

# Search for ctags file in parent directories, until you hit $HOME
hook global KakBegin .* %{
    evaluate-commands %sh{
        path="$PWD"
        while [ "$path" != "$HOME" ] && [ "$path" != "/" ]; do
            if [ -e "./tags" ]; then
                printf "%s\n" "set-option -add current ctagsfiles %{$path/tags}"
                break
            else
                cd ..
                path="$PWD"
            fi
        done
    }
}

## PLUGIN CONFIGURATION
# Initialize autoload and plugin dirctories
evaluate-commands %sh{
    autoload="$kak_config/autoload"
    plugins="$kak_config/plugins"
	if [ ! -e "$autoload" ]; then
	    mkdir -p "$autoload"
		ln -s /usr/share/kak/autoload "$autoload/default"
	fi
	if [ ! -e "$plugins" ]; then
        mkdir -p "$plugins"
		git -C "$plugins/" clone -q https://github.com/andreyorst/plug.kak.git
    fi
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
set-option current plug_git_domain "https://github.com/"

# Install plug.kak
plug "andreyorst/plug.kak" noload

# Install autopairs.kak
plug "alexherbo2/auto-pairs.kak" config %{
    enable-auto-pairs
}

# Install fzf.kak
plug "andreyorst/fzf.kak" config %{
    map global user f %{:fzf-mode<ret>} -docstring "fzf mode"
} defer fzf %{
    # Ubuntu 20.04 fzf is too old to support preview features (needs --preview-window=\${pos}:+{2}-{/2})
    # Set this to true if on >= 22.04
    set-option current fzf_preview false
} defer fzf-grep %{
    set-option global fzf_grep_command rg
    # Set this to true if on >= 22.04
    set-option global fzf_grep_preview false
}
